### ISSUE TITLE
Strange problem

### ISSUE THREAD

**Issue by ghost** [medariox/Scrapeer#11] opened 2017-03-18 22:28 UTC
Hi i have try to run a basic example on my computer & unfortunately i obtain a blank page without any error 

On my debian server it's working ( but no in my pc ) 
sorry for my bad english

```
`<?php

require_once 'scraper.php';


$scraper = new Scrapeer\Scraper();

$tracker = array('udp://public.popcorn-tracker.org:6969/announce',
    'http://182.176.139.129:6969/announce',
    'http://5.79.83.193:2710/announce',
    'http://91.218.230.81:6969/announce',
    'http://bt01.nnm-club.cc:2710/announce',
    'http://atrack.pow7.com/announce');

$hash = array( '0e1b1a2f5be209e1157c148faaf8afd3a3aa3824' );

$info = $scraper->scrape( $hash, $tracker );

print_r( $info );`
```

Possible to help me , thx very much

**Comment by medariox** [comment] 2017-03-18 23:05
"Blank page" means that all the trackers failed aka no result to show.

What you are looking for is error logging, have a look at the [Advanced usage examples - Error logging](https://github.com/medariox/Scrapeer#error-logging). That should solve your question.

For your example:
```<?php
require_once 'scraper.php';

$scraper = new Scrapeer\Scraper();

$tracker = array('udp://public.popcorn-tracker.org:6969/announce',
    'http://182.176.139.129:6969/announce',
    'http://5.79.83.193:2710/announce',
    'http://91.218.230.81:6969/announce',
    'http://bt01.nnm-club.cc:2710/announce',
    'http://atrack.pow7.com/announce');

$hash = array( '0e1b1a2f5be209e1157c148faaf8afd3a3aa3824' );

$info = $scraper->scrape( $hash, $tracker );

print_r( $info );`

// Check if we have any errors.
if ( $scraper->has_errors() ) {
    // Get the errors and print them.
    print_r( $scraper->get_errors() );
}
```

**Comment by ghost** [comment] 2017-03-18 23:08
Ok thx also i have try to add multiple trackers (10) , but in the response i have only the stats of the first tracker ...

i am forced to do this dirty code 

```
require 'scraper.php';

$trackers = array('udp://tracker.opentrackr.org:1337/announce','udp://tracker.leechers-paradise.org:6969','udp://tracker.internetwarriors.net:1337','udp://tracker.zer0day.to:1337/announce');


$scraper = new Scrapeer\Scraper();

$hash = 'A37279895DEEC8419B9FA3D076B1C036A31F1AC1';

// Init var
$seeders = 0;
$completed = 0;
$leechers = 0;

foreach($trackers as $tracker) {
	$info = $scraper->scrape(array($hash),array($tracker),1,1);
	$seeders += $info[$hash]['seeders'];
	$completed += $info[$hash]['completed'];
	$leechers += $info[$hash]['leechers'];
}

echo 'seeders : '.$seeders.' completed : '.$completed.' leechers : '.$leechers;
```

**Comment by medariox** [comment] 2017-03-19 15:44
By design Scrapeer only returns the stats from the first available tracker and stops.

**Comment by medariox** [comment] 2017-03-23 14:57
Closing this now. If you have any other questions, please open a new issue.

**Closed as completed by medariox** 2017-03-23 14:57 UTC
