### ISSUE TITLE
Is it possible to get the PeerID from the tracker?

### ISSUE THREAD

**Issue by foreaser** [medariox/Scrapeer#26] opened 2021-11-23 19:55 UTC
Is it possible to get the Peer ID of a Peer with a specific info_hash from HTTP or UDP tracker?

**Comment by medariox** [comment] 2021-11-27 10:17
Hey!

I think this is a duplicate of: https://github.com/medariox/scrapeer/issues/14

The announce request differs a lot from tracker to tracker, so it's not very feasible to implement.

**Closed as completed by medariox** 2021-11-27 10:17 UTC
